name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ...

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    container:
      image: ...
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_PORT: 5432
          POSTGRES_USER: kubsu
        ports:
          - 5432:5432
    steps:
      ...

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      ...

 verify:
   runs-on: ubuntu-latest
   steps:
     ...
